# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(552, 500)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")

        main_layout = QtWidgets.QVBoxLayout(Form)
        main_layout.setContentsMargins(10, 10, 10, 10)
        main_layout.setSpacing(10)

        # === SEARCH AREA ===
        self.search_widget = QtWidgets.QWidget(Form)
        self.search_widget.setStyleSheet("""
        QLineEdit {
            padding: 5px;
            font-size: 20px;
            border: 1px solid #5DADE2;
            border-radius: 6px;
        }
        QPushButton {
            background-color: #3498DB;
            color: white;
            padding: 5px 15px;
            border-radius: 6px;
        }
        QPushButton:hover {
            background-color: #2980B9;
        }
        QTableView {
            background-color: #f9f9f9;
            border: 1px solid #ccc;
            border-radius: 8px;
            gridline-color: #ddd;
        }
        QHeaderView::section {
            background-color: #3498DB;
            color: white;
            padding: 4px;
            border: 1px solid #ccc;
            border-radius: 6px;
        }
        QTableView QTableCornerButton::section {
            background-color: #f9f9f9;
        }
        QTableView::item {
            padding: 8px;
            border-bottom: 1px solid #eee;
        }
        QTableView::item:selected {
            background-color: #3498DB;
            color: white;
        }
        """)
        vbox = QtWidgets.QVBoxLayout(self.search_widget)
        hbox_search = QtWidgets.QHBoxLayout()
        self.search = QtWidgets.QLineEdit(self.search_widget)
        self.search.setObjectName("search")
        self.search_button = QtWidgets.QPushButton(self.search_widget)
        self.search_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\icons8-search-128.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.search_button.setIcon(icon)
        self.search_button.setIconSize(QtCore.QSize(28, 28))
        self.search_button.setObjectName("search_button")
        hbox_search.addWidget(self.search)
        hbox_search.addWidget(self.search_button)

        self.result = QtWidgets.QTableView(self.search_widget)
        self.result.setObjectName("result")

        self.add_to_notebook = QtWidgets.QPushButton(self.search_widget)
        self.add_to_notebook.setObjectName("add_to_notebook")
        self.add_to_notebook.setText("Thêm vào Sổ tay")

        vbox.addLayout(hbox_search)
        vbox.addWidget(self.result)
        vbox.addWidget(self.add_to_notebook)
        vbox.setStretch(1, 3)
        main_layout.addWidget(self.search_widget)

        # === TIP & STREAK AREA ===
        self.tip_streak_widget = QtWidgets.QWidget(Form)
        self.tip_streak_widget.setStyleSheet("""
        QWidget {
            background-color: #f9f9f9;
        }
        QLabel {
            font-size: 16px;
            color: #333;
            margin: 10px 0;
        }
        QPushButton {
            background-color: #3498DB;
            color: white;
            padding: 8px;
            border-radius: 6px;
            font-size: 14px;
        }
        QPushButton:hover {
            background-color: #2980B9;
        }
        """)
        tip_layout = QtWidgets.QVBoxLayout(self.tip_streak_widget)

        # Tips and Streak Labels
        info_layout = QtWidgets.QHBoxLayout()
        self.label = QtWidgets.QLabel("Mẹo học mỗi ngày", self.tip_streak_widget)
        self.tips = QtWidgets.QLabel("", self.tip_streak_widget)
        info_layout.addWidget(self.label)
        info_layout.addWidget(self.tips, 1)
        tip_layout.addLayout(info_layout)

        streak_layout = QtWidgets.QHBoxLayout()
        self.label_2 = QtWidgets.QLabel("Chuỗi học", self.tip_streak_widget)
        self.streak = QtWidgets.QLabel("", self.tip_streak_widget)
        streak_layout.addWidget(self.label_2)
        streak_layout.addWidget(self.streak, 1)
        tip_layout.addLayout(streak_layout)

        # Day buttons
        self.days_layout = QtWidgets.QHBoxLayout()
        self.mon = QtWidgets.QPushButton("T2", self.tip_streak_widget)
        self.tues = QtWidgets.QPushButton("T3", self.tip_streak_widget)
        self.wednes = QtWidgets.QPushButton("T4", self.tip_streak_widget)
        self.thurs = QtWidgets.QPushButton("T5", self.tip_streak_widget)
        self.fri = QtWidgets.QPushButton("T6", self.tip_streak_widget)
        self.satur = QtWidgets.QPushButton("T7", self.tip_streak_widget)
        self.sun = QtWidgets.QPushButton("CN", self.tip_streak_widget)
        for btn in [self.mon, self.tues, self.wednes, self.thurs, self.fri, self.satur, self.sun]:
            self.days_layout.addWidget(btn)

        tip_layout.addLayout(self.days_layout)
        main_layout.addWidget(self.tip_streak_widget)

        QtCore.QMetaObject.connectSlotsByName(Form)
