# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(717, 581)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_only_widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(31, 149, 239);\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    height: 30px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: #F5FAFE;\n"
"    color: #1F95EF;\n"
"    font-weight:bold;\n"
"}\n"
"")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.icon_only_widget)
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\chinese.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_page_button1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.home_page_button1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\icons8-home-32 (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\icons8-home-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.home_page_button1.setIcon(icon)
        self.home_page_button1.setIconSize(QtCore.QSize(20, 20))
        self.home_page_button1.setCheckable(True)
        self.home_page_button1.setAutoExclusive(True)
        self.home_page_button1.setObjectName("home_page_button1")
        self.verticalLayout.addWidget(self.home_page_button1)
        self.notebook_button1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.notebook_button1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\icons8-literature-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\ook_mau.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.notebook_button1.setIcon(icon1)
        self.notebook_button1.setIconSize(QtCore.QSize(20, 20))
        self.notebook_button1.setCheckable(True)
        self.notebook_button1.setAutoExclusive(True)
        self.notebook_button1.setObjectName("notebook_button1")
        self.verticalLayout.addWidget(self.notebook_button1)
        self.review_button1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.review_button1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\icons8-test-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\est_mau.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.review_button1.setIcon(icon2)
        self.review_button1.setIconSize(QtCore.QSize(20, 20))
        self.review_button1.setCheckable(True)
        self.review_button1.setAutoExclusive(True)
        self.review_button1.setObjectName("review_button1")
        self.verticalLayout.addWidget(self.review_button1)
        self.profile_button1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.profile_button1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\icons8-administrator-male-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\icons8-admin-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.profile_button1.setIcon(icon3)
        self.profile_button1.setIconSize(QtCore.QSize(20, 20))
        self.profile_button1.setCheckable(True)
        self.profile_button1.setAutoExclusive(True)
        self.profile_button1.setObjectName("profile_button1")
        self.verticalLayout.addWidget(self.profile_button1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 289, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.sign_out_button1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.sign_out_button1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\icons8-sign-out-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sign_out_button1.setIcon(icon4)
        self.sign_out_button1.setIconSize(QtCore.QSize(20, 20))
        self.sign_out_button1.setCheckable(True)
        self.sign_out_button1.setObjectName("sign_out_button1")
        self.verticalLayout_3.addWidget(self.sign_out_button1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.icon_name_widget = QtWidgets.QWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.icon_name_widget.setFont(font)
        self.icon_name_widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(31, 149, 239);\n"
"    color:white\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    text-align: left;\n"
"    height: 30px;\n"
"    border: none;\n"
"    padding-left: 10px;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: #F5FAFE;\n"
"    color: #1F95EF;\n"
"    font-weight:bold;\n"
"}")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.icon_name_widget)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\chinese.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.icon_name_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_page_button2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_page_button2.setFont(font)
        self.home_page_button2.setIcon(icon)
        self.home_page_button2.setIconSize(QtCore.QSize(20, 20))
        self.home_page_button2.setCheckable(True)
        self.home_page_button2.setAutoExclusive(True)
        self.home_page_button2.setObjectName("home_page_button2")
        self.verticalLayout_2.addWidget(self.home_page_button2)
        self.notebook_button2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.notebook_button2.setFont(font)
        self.notebook_button2.setIcon(icon1)
        self.notebook_button2.setIconSize(QtCore.QSize(20, 20))
        self.notebook_button2.setCheckable(True)
        self.notebook_button2.setAutoExclusive(True)
        self.notebook_button2.setObjectName("notebook_button2")
        self.verticalLayout_2.addWidget(self.notebook_button2)
        self.review_button2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.review_button2.setFont(font)
        self.review_button2.setIcon(icon2)
        self.review_button2.setIconSize(QtCore.QSize(20, 20))
        self.review_button2.setCheckable(True)
        self.review_button2.setAutoExclusive(True)
        self.review_button2.setObjectName("review_button2")
        self.verticalLayout_2.addWidget(self.review_button2)
        self.profile_button2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.profile_button2.setFont(font)
        self.profile_button2.setIcon(icon3)
        self.profile_button2.setIconSize(QtCore.QSize(20, 20))
        self.profile_button2.setCheckable(True)
        self.profile_button2.setAutoExclusive(True)
        self.profile_button2.setObjectName("profile_button2")
        self.verticalLayout_2.addWidget(self.profile_button2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 289, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.sign_out_button2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sign_out_button2.setFont(font)
        self.sign_out_button2.setIcon(icon4)
        self.sign_out_button2.setIconSize(QtCore.QSize(20, 20))
        self.sign_out_button2.setCheckable(True)
        self.sign_out_button2.setObjectName("sign_out_button2")
        self.verticalLayout_4.addWidget(self.sign_out_button2)
        self.gridLayout.addWidget(self.icon_name_widget, 0, 1, 1, 1)
        self.main_menu = QtWidgets.QWidget(parent=self.centralwidget)
        self.main_menu.setObjectName("main_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_menu)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.header = QtWidgets.QWidget(parent=self.main_menu)
        self.header.setObjectName("header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menu_button = QtWidgets.QPushButton(parent=self.header)
        self.menu_button.setStyleSheet("border:none;")
        self.menu_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_button.setIcon(icon5)
        self.menu_button.setIconSize(QtCore.QSize(30, 30))
        self.menu_button.setCheckable(True)
        self.menu_button.setObjectName("menu_button")
        self.horizontalLayout_3.addWidget(self.menu_button)
        spacerItem2 = QtWidgets.QSpacerItem(392, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.sign_in_button = QtWidgets.QPushButton(parent=self.header)
        self.sign_in_button.setStyleSheet("border:none;")
        self.sign_in_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\ser.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sign_in_button.setIcon(icon6)
        self.sign_in_button.setIconSize(QtCore.QSize(20, 20))
        self.sign_in_button.setObjectName("sign_in_button")
        self.horizontalLayout_3.addWidget(self.sign_in_button)
        self.verticalLayout_5.addWidget(self.header)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main_menu)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.homepage = QtWidgets.QWidget()
        self.homepage.setObjectName("homepage")
        self.stackedWidget.addWidget(self.homepage)
        self.notebookpage = QtWidgets.QWidget()
        self.notebookpage.setObjectName("notebookpage")
        self.stackedWidget.addWidget(self.notebookpage)
        self.reviewpage = QtWidgets.QWidget()
        self.reviewpage.setObjectName("reviewpage")
        self.stackedWidget.addWidget(self.reviewpage)
        self.profilepage = QtWidgets.QWidget()
        self.profilepage.setObjectName("profilepage")
        self.stackedWidget.addWidget(self.profilepage)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.main_menu, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.menu_button.toggled['bool'].connect(self.icon_only_widget.setHidden) # type: ignore
        self.menu_button.toggled['bool'].connect(self.icon_name_widget.setVisible) # type: ignore
        self.profile_button1.toggled['bool'].connect(self.profile_button2.setChecked) # type: ignore
        self.review_button1.toggled['bool'].connect(self.review_button2.setChecked) # type: ignore
        self.notebook_button1.toggled['bool'].connect(self.notebook_button2.setChecked) # type: ignore
        self.home_page_button1.toggled['bool'].connect(self.home_page_button2.setChecked) # type: ignore
        self.home_page_button2.toggled['bool'].connect(self.home_page_button1.setChecked) # type: ignore
        self.notebook_button2.toggled['bool'].connect(self.notebook_button1.setChecked) # type: ignore
        self.review_button2.toggled['bool'].connect(self.review_button1.setChecked) # type: ignore
        self.profile_button2.toggled['bool'].connect(self.profile_button1.setChecked) # type: ignore
        self.sign_out_button1.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.sign_out_button2.toggled['bool'].connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "MENU"))
        self.home_page_button2.setText(_translate("MainWindow", "Trang chủ"))
        self.notebook_button2.setText(_translate("MainWindow", "Sổ tay"))
        self.review_button2.setText(_translate("MainWindow", "Ôn tập"))
        self.profile_button2.setText(_translate("MainWindow", "Cá nhân"))
        self.sign_out_button2.setText(_translate("MainWindow", "Đăng xuất"))
