# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(0, -20, 401, 341))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #ecf0f1;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    font-size: 14px;\n"
"    background-color: white;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2980b9;\n"
"}\n"
"\n"
"QPushButton#login_button {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54a0ff;  /* khi rê chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e70bf;  /* khi nhấn */\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2e86de;  \n"
"    color: white;              \n"
"    border-radius: 10px;       \n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.dang_ky_button = QtWidgets.QPushButton(parent=self.widget)
        self.dang_ky_button.setGeometry(QtCore.QRect(160, 210, 91, 31))
        self.dang_ky_button.setObjectName("dang_ky_button")
        self.return_button = QtWidgets.QPushButton(parent=self.widget)
        self.return_button.setGeometry(QtCore.QRect(120, 260, 171, 31))
        self.return_button.setObjectName("return_button")
        self.layoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 110, 301, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ten_dang_nhap = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.ten_dang_nhap.setStyleSheet("")
        self.ten_dang_nhap.setObjectName("ten_dang_nhap")
        self.verticalLayout.addWidget(self.ten_dang_nhap)
        self.mat_khau = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.mat_khau.setStyleSheet("")
        self.mat_khau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.mat_khau.setObjectName("mat_khau")
        self.verticalLayout.addWidget(self.mat_khau)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 60, 60))
        self.label_2.setMinimumSize(QtCore.QSize(60, 60))
        self.label_2.setMaximumSize(QtCore.QSize(60, 60))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\VS Code\CHINESE_APP\icon\chinese.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dang_ky_button.setText(_translate("Dialog", "Đăng ký"))
        self.return_button.setText(_translate("Dialog", "Quay lại đăng nhập"))
        self.label_4.setText(_translate("Dialog", "Tên đăng nhập"))
        self.label_5.setText(_translate("Dialog", "Mật khẩu"))
